//! Generate or check `CLAUDE_INDEX.md` from the on-disk `CLAUDE.md` hierarchy.
//!
//! Usage:
//!   `gen-claude-index`            # write `CLAUDE_INDEX.md`
//!   `gen-claude-index --check`    # exit non-zero if it would differ

use std::fs;
use std::path::{Path, PathBuf};

const EXCLUDED: &[&str] = &[
    "target",
    ".git",
    ".github",
    "node_modules",
    ".idea",
    ".vscode",
];

#[derive(Debug)]
struct Node {
    path: PathBuf,
    one_liner: String,
    children: Vec<Node>,
}

fn read_one_liner(claude_md: &Path) -> String {
    let Ok(s) = fs::read_to_string(claude_md) else {
        return String::new();
    };
    for line in s.lines() {
        let t = line.trim();
        if t.starts_with("> ") {
            return t.trim_start_matches('>').trim().to_string();
        }
    }
    String::new()
}

fn collect(dir: &Path, root: &Path) -> Option<Node> {
    let claude = dir.join("CLAUDE.md");
    if !claude.exists() {
        return None;
    }
    let mut children: Vec<Node> = Vec::new();
    if let Ok(rd) = fs::read_dir(dir) {
        let mut entries: Vec<_> = rd.flatten().collect();
        entries.sort_by_key(std::fs::DirEntry::file_name);
        for entry in entries {
            let p = entry.path();
            if !p.is_dir() {
                continue;
            }
            let name = entry.file_name().to_string_lossy().to_string();
            if EXCLUDED.contains(&name.as_str()) || name.starts_with('.') {
                continue;
            }
            if let Some(c) = collect(&p, root) {
                children.push(c);
            }
        }
    }
    let rel = dir.strip_prefix(root).unwrap_or(dir).to_path_buf();
    Some(Node {
        path: rel,
        one_liner: read_one_liner(&claude),
        children,
    })
}

fn render(node: &Node, depth: usize, out: &mut String) {
    if depth > 0 {
        let indent = "  ".repeat(depth - 1);
        let path = node.path.display().to_string().replace('\\', "/");
        let claude_link = if path.is_empty() {
            "CLAUDE.md".to_string()
        } else {
            format!("{path}/CLAUDE.md")
        };
        let label = if path.is_empty() {
            "/".to_string()
        } else {
            format!("{path}/")
        };
        let line = if node.one_liner.is_empty() {
            format!("{indent}- [`{label}`]({claude_link})\n")
        } else {
            format!(
                "{indent}- [`{label}`]({claude_link}) — {}\n",
                node.one_liner
            )
        };
        out.push_str(&line);
    }
    for c in &node.children {
        render(c, depth + 1, out);
    }
}

fn build(root: &Path) -> String {
    let mut out = String::new();
    out.push_str("# CLAUDE Structure Index\n\n");
    out.push_str("> Auto-generated by `scripts/gen-claude-index`. Do not edit by hand.\n");
    out.push_str("> See `CONSTITUTION.md` §3.\n\n");
    if let Some(root_node) = collect(root, root) {
        for c in &root_node.children {
            render(c, 1, &mut out);
        }
    } else {
        out.push_str("_(no CLAUDE.md at root)_\n");
    }
    out
}

fn scan_missing(dir: &Path, root: &Path, out: &mut Vec<PathBuf>) {
    if !dir.join("CLAUDE.md").exists() {
        out.push(dir.strip_prefix(root).unwrap_or(dir).to_path_buf());
    }
    if let Ok(rd) = fs::read_dir(dir) {
        for entry in rd.flatten() {
            let p = entry.path();
            if !p.is_dir() {
                continue;
            }
            let name = entry.file_name().to_string_lossy().to_string();
            if EXCLUDED.contains(&name.as_str()) || name.starts_with('.') {
                continue;
            }
            scan_missing(&p, root, out);
        }
    }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let check = args.iter().any(|a| a == "--check");
    let presence_only = args.iter().any(|a| a == "--presence");

    let root = std::env::current_dir().expect("cwd");

    // Presence enforcement
    let mut missing = Vec::new();
    scan_missing(&root, &root, &mut missing);
    if !missing.is_empty() {
        eprintln!("Missing CLAUDE.md in:");
        for m in &missing {
            eprintln!("  - {}", m.display());
        }
        if check || presence_only {
            std::process::exit(2);
        }
    } else if presence_only {
        println!("All directories have CLAUDE.md.");
        return;
    }

    let generated = build(&root);
    let target = root.join("CLAUDE_INDEX.md");

    if check {
        let existing = fs::read_to_string(&target).unwrap_or_default();
        if normalize(&existing) != normalize(&generated) {
            eprintln!("CLAUDE_INDEX.md is stale. Run `gen-claude-index` to update.");
            std::process::exit(1);
        }
        println!("CLAUDE_INDEX.md up to date.");
    } else {
        fs::write(&target, &generated).expect("write CLAUDE_INDEX.md");
        println!("wrote {}", target.display());
    }
}

fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n").trim_end().to_string()
}
